/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.liliangshan.poi

import kotlin.test.Test

class ApplicationTest {

    @Test
    fun testAppHasAGreeting() {
    }
}
